language: go
sudo: false

go:
  - "1.12"
  - "1.13"
  - "stable"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - PG_URI=postgres://postgres@localhost:5432/pgadapter?sslmode=disable

before_install:
  - psql -c 'create database pgadapter;' -U postgres
  - env GO111MODULE=on go mod vendor

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
